// Mock weather data to avoid API rate limiting
export const mockWeatherData = [
  {
    cityName: "New York",
    temp: 72.5,
    app_temp: 75.2,
    weather: { description: "Partly cloudy" },
    rh: 65,
    wind_spd: 8.3,
    wind_cdir: "NW",
    pres: 1013.2,
    vis: 10.0,
    uv: 6.2,
    clouds: 40,
    timezone: "America/New_York",
    station: "KNYC",
  },
  {
    cityName: "Los Angeles",
    temp: 78.1,
    app_temp: 79.5,
    weather: { description: "Clear sky" },
    rh: 55,
    wind_spd: 5.7,
    wind_cdir: "W",
    pres: 1015.8,
    vis: 12.0,
    uv: 8.1,
    clouds: 10,
    timezone: "America/Los_Angeles",
    station: "KLAX",
  },
  {
    cityName: "Chicago",
    temp: 68.9,
    app_temp: 71.3,
    weather: { description: "Overcast clouds" },
    rh: 72,
    wind_spd: 12.1,
    wind_cdir: "NE",
    pres: 1009.5,
    vis: 8.5,
    uv: 4.3,
    clouds: 85,
    timezone: "America/Chicago",
    station: "KCHI",
  },
  {
    cityName: "Houston",
    temp: 85.2,
    app_temp: 92.1,
    weather: { description: "Scattered clouds" },
    rh: 78,
    wind_spd: 6.8,
    wind_cdir: "S",
    pres: 1012.1,
    vis: 9.2,
    uv: 9.5,
    clouds: 35,
    timezone: "America/Chicago",
    station: "KHOU",
  },
  {
    cityName: "Phoenix",
    temp: 95.4,
    app_temp: 98.7,
    weather: { description: "Clear sky" },
    rh: 25,
    wind_spd: 4.2,
    wind_cdir: "E",
    pres: 1008.9,
    vis: 15.0,
    uv: 11.2,
    clouds: 5,
    timezone: "America/Phoenix",
    station: "KPHX",
  },
  {
    cityName: "Philadelphia",
    temp: 71.8,
    app_temp: 74.1,
    weather: { description: "Few clouds" },
    rh: 68,
    wind_spd: 7.9,
    wind_cdir: "NW",
    pres: 1014.3,
    vis: 11.0,
    uv: 5.8,
    clouds: 20,
    timezone: "America/New_York",
    station: "KPHL",
  },
  {
    cityName: "San Antonio",
    temp: 88.7,
    app_temp: 94.2,
    weather: { description: "Partly cloudy" },
    rh: 62,
    wind_spd: 8.1,
    wind_cdir: "SE",
    pres: 1011.7,
    vis: 10.5,
    uv: 8.9,
    clouds: 45,
    timezone: "America/Chicago",
    station: "KSAT",
  },
  {
    cityName: "San Diego",
    temp: 75.3,
    app_temp: 76.8,
    weather: { description: "Clear sky" },
    rh: 58,
    wind_spd: 6.4,
    wind_cdir: "W",
    pres: 1016.2,
    vis: 12.5,
    uv: 7.6,
    clouds: 15,
    timezone: "America/Los_Angeles",
    station: "KSAN",
  },
  {
    cityName: "Dallas",
    temp: 82.6,
    app_temp: 87.3,
    weather: { description: "Scattered clouds" },
    rh: 69,
    wind_spd: 9.2,
    wind_cdir: "S",
    pres: 1010.8,
    vis: 9.8,
    uv: 8.4,
    clouds: 40,
    timezone: "America/Chicago",
    station: "KDAL",
  },
  {
    cityName: "San Jose",
    temp: 73.9,
    app_temp: 75.1,
    weather: { description: "Few clouds" },
    rh: 52,
    wind_spd: 5.3,
    wind_cdir: "NW",
    pres: 1017.1,
    vis: 11.8,
    uv: 7.2,
    clouds: 25,
    timezone: "America/Los_Angeles",
    station: "KSJC",
  },
  {
    cityName: "Austin",
    temp: 86.1,
    app_temp: 91.4,
    weather: { description: "Partly cloudy" },
    rh: 64,
    wind_spd: 7.6,
    wind_cdir: "S",
    pres: 1012.4,
    vis: 10.2,
    uv: 9.1,
    clouds: 50,
    timezone: "America/Chicago",
    station: "KAUS",
  },
  {
    cityName: "Jacksonville",
    temp: 81.3,
    app_temp: 86.7,
    weather: { description: "Thunderstorm" },
    rh: 82,
    wind_spd: 11.4,
    wind_cdir: "E",
    pres: 1009.2,
    vis: 6.5,
    uv: 3.8,
    clouds: 90,
    timezone: "America/New_York",
    station: "KJAX",
  },
  {
    cityName: "Miami",
    temp: 84.7,
    app_temp: 92.3,
    weather: { description: "Scattered clouds" },
    rh: 75,
    wind_spd: 8.9,
    wind_cdir: "SE",
    pres: 1013.6,
    vis: 9.1,
    uv: 10.3,
    clouds: 35,
    timezone: "America/New_York",
    station: "KMIA",
  },
  {
    cityName: "Seattle",
    temp: 62.4,
    app_temp: 64.1,
    weather: { description: "Light rain" },
    rh: 88,
    wind_spd: 6.7,
    wind_cdir: "W",
    pres: 1018.9,
    vis: 7.2,
    uv: 2.1,
    clouds: 95,
    timezone: "America/Los_Angeles",
    station: "KSEA",
  },
  {
    cityName: "Denver",
    temp: 69.8,
    app_temp: 71.2,
    weather: { description: "Few clouds" },
    rh: 45,
    wind_spd: 9.8,
    wind_cdir: "W",
    pres: 1005.3,
    vis: 13.5,
    uv: 7.9,
    clouds: 20,
    timezone: "America/Denver",
    station: "KDEN",
  },
  {
    cityName: "Boston",
    temp: 67.2,
    app_temp: 69.8,
    weather: { description: "Overcast clouds" },
    rh: 71,
    wind_spd: 10.3,
    wind_cdir: "NE",
    pres: 1016.7,
    vis: 8.9,
    uv: 4.6,
    clouds: 80,
    timezone: "America/New_York",
    station: "KBOS",
  },
  {
    cityName: "Las Vegas",
    temp: 92.1,
    app_temp: 94.8,
    weather: { description: "Clear sky" },
    rh: 22,
    wind_spd: 3.8,
    wind_cdir: "E",
    pres: 1007.4,
    vis: 16.0,
    uv: 11.8,
    clouds: 0,
    timezone: "America/Los_Angeles",
    station: "KLAS",
  },
  {
    cityName: "Portland",
    temp: 65.7,
    app_temp: 67.3,
    weather: { description: "Light rain" },
    rh: 85,
    wind_spd: 5.9,
    wind_cdir: "W",
    pres: 1019.2,
    vis: 7.8,
    uv: 2.4,
    clouds: 90,
    timezone: "America/Los_Angeles",
    station: "KPDX",
  },
  {
    cityName: "Nashville",
    temp: 76.4,
    app_temp: 80.1,
    weather: { description: "Partly cloudy" },
    rh: 66,
    wind_spd: 7.2,
    wind_cdir: "S",
    pres: 1011.9,
    vis: 10.8,
    uv: 6.7,
    clouds: 45,
    timezone: "America/Chicago",
    station: "KBNA",
  },
  {
    cityName: "Atlanta",
    temp: 79.3,
    app_temp: 83.6,
    weather: { description: "Scattered clouds" },
    rh: 73,
    wind_spd: 6.1,
    wind_cdir: "SE",
    pres: 1012.8,
    vis: 9.6,
    uv: 7.8,
    clouds: 40,
    timezone: "America/New_York",
    station: "KATL",
  },
]
